IPS-9 Revert "Is that needed?" -> Yes, it is.
This reverts commit 99fc979fc4e5b4fbd3673e8b403563f95dc3c5f2.

In file included from src_pEp4ipsec/pEpObjCAdapter/Subprojects/PEPObjCTypeUtils/PEPObjCTypeUtils/PEPMessage+ASN1.m:11:
src_pEp4ipsec/pEpEngine/build-mac/build/include/pEp/map_asn1.h:11:10: fatal error: 'ASN1Message.h' file not found